plugins {
	id 'fabric-loom' version "1.11.7"
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

repositories {
    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven"
        content {
            includeGroup "maven.modrinth"
        }
    }
    mavenCentral()
    maven { url = "https://maven.shedaniel.me" }
	maven {
		url 'https://jitpack.io'
	}
	maven { url 'https://maven.wispforest.io/releases/' }
}

loom {
    //splitEnvironmentSourceSets()

    mixin {
		defaultRefmapName = "12th-client.refmap.json"
	}
	accessWidenerPath = file("src/main/resources/12th-client.accesswidener")
}


dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

    // OWO as a normal mod dependency (not shaded)
    modImplementation "io.wispforest:owo-lib:${project.owo_version}"

    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    modImplementation "maven.modrinth:notenoughcrashes:4.4.9+1.21.1-fabric"

    implementation 'com.google.code.gson:gson:2.10.1'

    // You DO want discord-rpc shaded, so keep this:
    include implementation('com.github.Vatuu:discord-rpc:1.6.2')
}

jar {
    manifest {
        attributes(
                'Main-Class': 'com.noadsch12.Launcher'
        )
    }
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": inputs.properties.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 21
}

java {
	// Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
	// if it is present.
	// If you remove this line, sources will not be generated.
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}